name: cloud function trigger

inputs:
  projectname:
    description: ""
  repository:
    description: ""
  runtime:
    description: ""
  region:
    description: ""
  job_folder_location:
    description: ""
  entry_point:
    description: ""
  run_service_account:
    description: ""
  timeout:
    description: ""
  memory:
    description: ""
  workload_identity_provider:
    description: ""
  service_account:
    description: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    
    - name: cloud function deployment
      shell: bash
      run: |
        gcloud functions deploy ${{ inputs.job_folder_location }} --gen2 --region=${{ inputs.region }} --runtime=${{ inputs.runtime }} --source=cloud-function/${{ inputs.job_folder_location }}/src --entry-point=${{ inputs.entry_point }} --trigger-http --service-account=${{ inputs.run_service_account }} --timeout=${{ inputs.timeout }} --memory=${{ inputs.memory }} --project=${{ inputs.projectname }} --quiet